# Generated by Django 6.0.5 on 2026-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='entrada', max_length=10)),
                ('autorizado', models.BooleanField(default=False)),
                ('metodo', models.CharField(default='facial', max_length=30)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('foto_captura', models.ImageField(blank=True, null=True, upload_to='capturas/%Y/%m/%d/')),
                ('observacion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
